"""Independent durable schema axes for autonomous TH105 learning."""

TRANSITION_SCHEMA_VERSION = 2
FEATURE_SCHEMA_VERSION = 1
ACTION_SCHEMA_VERSION = 4
CORPUS_SCHEMA_VERSION = 2
LEARNING_CURVE_SCHEMA_VERSION = 1
TRAINING_GENERATION = "autonomous-grammar-v4"
